name: generate pacman game

on:
  schedule: # Her 24 saatte bir otomatik olarak çalışır
    - cron: "0 */24 * * *"
  workflow_dispatch: # Manuel olarak da istediğiniz zaman çalıştırmanıza olanak tanır
  push: # Main branch'e her kod gönderildiğinde çalışır
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Push the generated SVG to the output branch
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
